# Load Data and preprocess

In [1]:
import sys
import os
sys.path.append(os.path.abspath(".."))

In [2]:
#pip install ucimlrepo

In [3]:
from src.data.load_data import load_input_data
from src.data.load_data import preprocess_data
#from src.data.load_data import preprocess_data_no_onehot

In [4]:
X_train, X_test, y_train, y_test, metadata, variables, datasetdf = load_input_data()

ConnectionError: Error connecting to server

In [ ]:
import pandas as pd
from src.data.load_data import preprocess_num

num_cols = ['Attribute2', 'Attribute5', 'Attribute8', 'Attribute11',
            'Attribute13', 'Attribute16', 'Attribute18']

X_train_raw,X_test_raw = X_train,X_test
#X_train, X_test, datasetdf = preprocess_data(X_train, X_test, datasetdf, num_cols)
X_train_num, X_test_num, datasetdf_num = preprocess_num(X_train, X_test, datasetdf, num_cols)
X_train, X_test, datasetdf = preprocess_data(X_train, X_test, datasetdf, num_cols)

#pd.set_option('display.max_columns', None)
#print(X_train.head())
print(datasetdf.head())

# Train model

In [6]:
from src.model.train_model import train_classifier
from src.model.train_model import train_classifier_LR

In [7]:
#clf = train_classifier(X_train,y_train,n_estimators=100, random_state=42) # this is for random forrest
clf = train_classifier_LR(X_train,y_train, random_state=42)

# Test model

In [8]:
from src.model.test_model import test_classifier_prediction

In [9]:
y_pred,classification_report,accuracy_score = test_classifier_prediction(clf,X_test,y_test)

In [10]:
print(accuracy_score)

0.78


In [11]:
print(classification_report)

              precision    recall  f1-score   support

           1       0.81      0.89      0.85       210
           2       0.67      0.52      0.59        90

    accuracy                           0.78       300
   macro avg       0.74      0.71      0.72       300
weighted avg       0.77      0.78      0.77       300


### User constraints / Ontology constraints

In [12]:
from src.ontology.generate_rules import *

In [13]:
X_train_positive = X_train_num[y_train==1]
X_train_negative = X_train_num[y_train==2]

In [14]:
positive_profile = summarize_features(X_train_positive)

In [15]:
positive_profile

{'Attribute1': {'A14': 0.49795918367346936,
  'A12': 0.23265306122448978,
  'A11': 0.20408163265306123,
  'A13': 0.0653061224489796},
 'Attribute2': {'mean': np.float64(-0.12780039106837582),
  'min': np.float64(-1.4027313562014667),
  'max': np.float64(3.281803416596071)},
 'Attribute3': {'A32': 0.5040816326530613,
  'A34': 0.3448979591836735,
  'A33': 0.09183673469387756,
  'A31': 0.03469387755102041,
  'A30': 0.024489795918367346},
 'Attribute4': {'A43': 0.2938775510204082,
  'A40': 0.23061224489795917,
  'A42': 0.17346938775510204,
  'A41': 0.12448979591836734,
  'A49': 0.09183673469387756,
  'A46': 0.03469387755102041,
  'A45': 0.02040816326530612,
  'A44': 0.014285714285714285,
  'A410': 0.00816326530612245,
  'A48': 0.00816326530612245},
 'Attribute5': {'mean': np.float64(-0.08150627549993873),
  'min': np.float64(-1.0710213212937136),
  'max': np.float64(4.65843030094252)},
 'Attribute6': {'A61': 0.5387755102040817,
  'A65': 0.21428571428571427,
  'A62': 0.11224489795918367,
  

In [16]:
negative_profile = summarize_features(X_train_negative)

In [17]:
negative_profile

{'Attribute1': {'A11': 0.4380952380952381,
  'A12': 0.3523809523809524,
  'A14': 0.1523809523809524,
  'A13': 0.05714285714285714},
 'Attribute2': {'mean': np.float64(0.2982009124928774),
  'min': np.float64(-1.2354265428872688),
  'max': np.float64(3.281803416596071)},
 'Attribute3': {'A32': 0.5476190476190477,
  'A34': 0.17142857142857143,
  'A33': 0.10476190476190476,
  'A31': 0.1,
  'A30': 0.0761904761904762},
 'Attribute4': {'A40': 0.2761904761904762,
  'A43': 0.2,
  'A42': 0.19523809523809524,
  'A49': 0.11428571428571428,
  'A46': 0.08571428571428572,
  'A41': 0.07142857142857142,
  'A45': 0.02857142857142857,
  'A44': 0.014285714285714285,
  'A410': 0.009523809523809525,
  'A48': 0.004761904761904762},
 'Attribute5': {'mean': np.float64(0.1901813094998568),
  'min': np.float64(-1.0354811381978963),
  'max': np.float64(4.767669600563347)},
 'Attribute6': {'A61': 0.7285714285714285,
  'A62': 0.12380952380952381,
  'A65': 0.09047619047619047,
  'A63': 0.03333333333333333,
  'A64':

In [18]:
#p_statistical = extract_statistical_rules(X_train_positive, X_train_raw, num_quantiles=(0.1, 0.9), cat_threshold=0.85)
p_statistical = extract_statistical_rules(X_train_positive, X_train_num, num_quantiles=(0.1, 0.9), cat_threshold=0.85)

In [19]:
p_statistical

{'Attribute2': (np.float64(-1.235), np.float64(1.274)),
 'Attribute5': (np.float64(-0.85), np.float64(1.224)),
 'Attribute8': (np.float64(-1.727), np.float64(0.945)),
 'Attribute10': 'A101',
 'Attribute11': (np.float64(-1.66), np.float64(1.076)),
 'Attribute13': (np.float64(-1.048), np.float64(1.419)),
 'Attribute16': (np.float64(-0.725), np.float64(1.074)),
 'Attribute18': (np.float64(-0.434), np.float64(2.304))}

In [20]:
p_permutation_imp_top_features = top_features(clf, X_train, y_train, n_repeats=5, random_state=42)

In [21]:
p_permutation_imp_top_features

['Attribute1_A14',
 'Attribute9_A93',
 'Attribute6_A65',
 'Attribute2',
 'Attribute12_A124',
 'Attribute3_A34',
 'Attribute8',
 'Attribute15_A153',
 'Attribute14_A143',
 'Attribute7_A74',
 'Attribute15_A152',
 'Attribute1_A12',
 'Attribute5']

In [22]:
p = combined_features(p_permutation_imp_top_features,p_statistical)

In [23]:
p

{'Attribute2': (np.float64(-1.235), np.float64(1.274)),
 'Attribute5': (np.float64(-0.85), np.float64(1.224)),
 'Attribute8': (np.float64(-1.727), np.float64(0.945)),
 'Attribute10': 'A101',
 'Attribute11': (np.float64(-1.66), np.float64(1.076)),
 'Attribute13': (np.float64(-1.048), np.float64(1.419)),
 'Attribute16': (np.float64(-0.725), np.float64(1.074)),
 'Attribute18': (np.float64(-0.434), np.float64(2.304)),
 'Attribute1': 'A14',
 'Attribute9': 'A93',
 'Attribute6': 'A65',
 'Attribute12': 'A124',
 'Attribute3': 'A34',
 'Attribute15': 'A153',
 'Attribute14': 'A143',
 'Attribute7': 'A74'}

In [24]:
p_num = {key: value for key, value in p.items() if isinstance(value, tuple)}
p_cat = {key: value for key, value in p.items() if isinstance(value, str)}
print(p_num)
print(p_cat)

{'Attribute2': (np.float64(-1.235), np.float64(1.274)), 'Attribute5': (np.float64(-0.85), np.float64(1.224)), 'Attribute8': (np.float64(-1.727), np.float64(0.945)), 'Attribute11': (np.float64(-1.66), np.float64(1.076)), 'Attribute13': (np.float64(-1.048), np.float64(1.419)), 'Attribute16': (np.float64(-0.725), np.float64(1.074)), 'Attribute18': (np.float64(-0.434), np.float64(2.304))}
{'Attribute10': 'A101', 'Attribute1': 'A14', 'Attribute9': 'A93', 'Attribute6': 'A65', 'Attribute12': 'A124', 'Attribute3': 'A34', 'Attribute15': 'A153', 'Attribute14': 'A143', 'Attribute7': 'A74'}


### Final outputs of Input section of pipeline
For experimentation, here are some values

In [25]:
from src.utilities.desired_space import desired_space
X_test_negative = X_test[y_test==2]
x= X_test_negative[0:1] #test instance #select first row as dataFrame
p_num = p_num
p_cat = p_cat
#p= {
    #'Attribute5':(0, 1) #credit amount #I put a normalized amount here
#}#perturbation map
#desired_space= desired_space(2, datasetdf) #all the feature vectors with output=2 #not preprocessed! Potential issue from authors!
#print(datasetdf.head())
desired_space = desired_space(1,datasetdf) #did preprocessing also to datasetdf
#print(X_train.head())
#print(desired_space.head())
cat_f= X_train.select_dtypes(include=['bool']) #categorical features
#print(cat_f)
num_f= X_train.select_dtypes(include=['int64', 'float64']) #numerical features
#print(num_f)
protect_f= ['Attribute9_A92'  'Attribute9_A93'  'Attribute9_A94', 'Attribute5'] # Personal status and sex (X_train.head() shows only 3 values (columns) while there are 5) #protected features
features= X_train.columns #all features
t= 2 #desired outcome
f= clf #black-box model for which we want to find CF
X= X_train #training data
step = {attribute:0.01 for attribute in p_num.keys()}
#step= {
#    'Attribute5': 0.01 #credit amount steps #tiny amount bc of normalized feature values
#} #dictionary holding the feature distribution to be used for single feature perturbation method

### Derived variables

In [26]:
f2change = p.keys()

# UFCE

### Feature Selection: Mutual Information (MI)

In [27]:
from itertools import combinations
from src.utilities.mutual_information import mi_score
from src.utilities.mutual_information import MI
feature_pairs = list(combinations(list(features), 2))
print(feature_pairs[:5])
mi_list = MI(feature_pairs, X_train) #used all features available #original authors do over entire X but it is not preprocessed... Which i think is nessecary? #also works for bool one-hot encoding 
# top 5 
print(mi_list[:5])

[('Attribute2', 'Attribute5'), ('Attribute2', 'Attribute8'), ('Attribute2', 'Attribute11'), ('Attribute2', 'Attribute13'), ('Attribute2', 'Attribute16')]
[('Attribute9_A92', 'Attribute9_A93'), ('Attribute2', 'Attribute5'), ('Attribute3_A32', 'Attribute3_A34'), ('Attribute17_A172', 'Attribute17_A173'), ('Attribute16', 'Attribute3_A32')]


### Nearest Neighbour: KD Tree

In [28]:
from src.utilities.nearest_neighbours import FNN
nn = FNN(desired_space,x,3.5) #radius arbitrarily set; can experiment with how close we want it to be to x #3.5 for euclidean distance is around 0.5 for each of the 48 features difference from x, get 3 datapoints
print(nn)

     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
255    3.281803    1.577658   -1.726666    -1.660121     -0.77365   

     Attribute16  Attribute18  Attribute1_A12  Attribute1_A13  Attribute1_A14  \
255    -0.724565    -0.434114            True           False           False   

     ...  Attribute12_A124  Attribute14_A142  Attribute14_A143  \
255  ...             False             False              True   

     Attribute15_A152  Attribute15_A153  Attribute17_A172  Attribute17_A173  \
255              True             False              True             False   

     Attribute17_A174  Attribute19_A192  Attribute20_A202  
255             False             False             False  

[1 rows x 48 columns]


### Subspace: Intervals

In [29]:
from src.utilities.nearest_neighbours import intervals
from src.utilities.nearest_neighbours import intervals2
#subspace = intervals(nn,p,f2change,x) 
subspace = intervals2(nn,p_num,p_cat,f2change,x)
print(subspace) #correct output

-1.235
1.274
-0.85
1.224
-1.727
0.945
-1.66
1.076
-1.048
1.419
-0.725
1.074
-0.434
2.304
subspace cat val.:  A101
subspace cat val.:  A14
subspace cat val.:  A93
subspace cat val.:  A65
subspace cat val.:  A124
subspace cat val.:  A34
subspace cat val.:  A153
subspace cat val.:  A143
subspace cat val.:  A74
{'Attribute2': [np.float64(3.281803416596071), np.float64(1.274)], 'Attribute5': [np.float64(1.577657587320882), np.float64(1.224)], 'Attribute8': [np.float64(-1.727), np.float64(-1.7266657450237146)], 'Attribute11': [np.float64(-1.66), np.float64(-1.6601212221718709)], 'Attribute13': [np.float64(-1.048), np.float64(-0.7736503003004547)], 'Attribute16': [np.float64(-0.725), np.float64(-0.7245647372489965)], 'Attribute18': [np.float64(-0.434), np.float64(-0.43411405009394055)], 'Attribute10': 'A101', 'Attribute1': 'A14', 'Attribute9': 'A93', 'Attribute6': 'A65', 'Attribute12': 'A124', 'Attribute3': 'A34', 'Attribute15': 'A153', 'Attribute14': 'A143', 'Attribute7': 'A74'}


### CF Generator: Single Feature

In [30]:
from src.utilities.UFCE import SF
#cf = SF(x,X,cat_f,p,f,t,step)
cf = SF(x,X_train,p_num,p_cat,f,t,step) # changed from X_train_raw to X_train
print(cf)

original x prediction:  [2]
all columns are 0 for this category, as it is the reference feature value


C:\Users\Jurjen\Desktop\Python exercises code (target level)\cf-enhancement-xai\src\utilities\UFCE.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  z.loc[:, relevant_columns] = 0
C:\Users\Jurjen\Desktop\Python exercises code (target level)\cf-enhancement-xai\src\utilities\UFCE.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  z.loc[:, relevant_columns] = 0
C:\Users\Jurjen\Desktop\Python exercises code (target level)\cf-enhancement-xai\src\utilities\UFCE.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype fi

     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
677    4.285632     0.89566   -0.835976    -0.747967    -1.047717   

     Attribute16  Attribute18  Attribute1_A12  Attribute1_A13  Attribute1_A14  \
677    -0.724565    -0.434114               0               0            True   

     ...  Attribute12_A124  Attribute14_A142  Attribute14_A143  \
677  ...             False             False              True   

     Attribute15_A152  Attribute15_A153  Attribute17_A172  Attribute17_A173  \
677              True             False             False              True   

     Attribute17_A174  Attribute19_A192  Attribute20_A202  
677             False             False             False  

[1 rows x 48 columns]


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LocalOutlierFactor was fitted with feature names
  warnings.warn(


### CF Generator: Double Features

In [31]:
from src.utilities.UFCE import DF
z = DF(datasetdf,x,X_train,subspace,mi_list,cat_f,num_f,features,protect_f,f,t)
print(z)

going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
[[ 2.88056839]
 [-1.23042764]
 [ 1.23616998]
 [ 0.87074811]
 [ 1.60159185]
 [-0.04280656]
 [ 1.60159185]
 [-0.04280656]
 [ 2.33243559]
 [-0.68229483]
 [-0.95636123]
 [-1.0477167 ]
 [-1.23042764]
 [ 2.24108012]
 [-0.68229483]
 [-0.31687296]
 [ 1.60159185]
 [-0.95636123]
 [ 0.77939264]
 [-0.40822843]
 [ 1.14481451]
 [ 0.77939264]
 [ 1.14481451]
 [ 0.77939264]
 [-0.86500577]
 [ 0.04854891]
 [ 0.32261531]
 [ 0.59668171]
 [-0.13416203]
 [ 2.51514652]
 [ 0.04854891]
 [-0.7736503 ]
 [-0.4995839 ]
 [ 1.96701372]
 [-0.2255175 ]
 [-0.95636123]
 [-0.40822843]
 [ 0.13990437]
 [ 0.13990437]
 [-1.0477167 ]
 [-0.4995839 ]
 [-0.86500577]
 [ 0.77939264]
 [-1.0477167 ]
 [ 2.05836919]
 

C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation

going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
g

In [32]:
print("original: ")
print(x)
print("counterfactual: ")
print(z)

original: 
     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
677    4.285632     0.89566   -0.835976    -0.747967    -1.047717   

     Attribute16  Attribute18  Attribute1_A12  Attribute1_A13  Attribute1_A14  \
677    -0.724565    -0.434114            True           False           False   

     ...  Attribute12_A124  Attribute14_A142  Attribute14_A143  \
677  ...             False             False              True   

     Attribute15_A152  Attribute15_A153  Attribute17_A172  Attribute17_A173  \
677              True             False             False              True   

     Attribute17_A174  Attribute19_A192  Attribute20_A202  
677             False             False             False  

[1 rows x 48 columns]
counterfactual: 
     Attribute2  Attribute5  Attribute8  Attribute11  Attribute13  \
677        1.76     0.89566   -0.835976    -0.631899    -1.047717   

     Attribute16  Attribute18  Attribute1_A12  Attribute1_A13  Attribute1_A14  \
677    -0.72456

In [33]:
print("Differences between original and counterfactual:")

# Compare x and z for all columns
differences = (x != z).iloc[0]

# Print only the differing columns with their values in x and z
for col in x.columns[differences]:
    print(f"{col}: original = {x.iloc[0][col]}, counterfactual = {z.iloc[0][col]}")

Differences between original and counterfactual:
Attribute2: original = 4.285632296481258, counterfactual = 1.76
Attribute11: original = -0.7479667044950186, counterfactual = -0.6318987038835711


# Evaluation

### Metrics: Plausible

### Metrics: Actionable

0.9384816753926701


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### Metrics: Feasible

NameError: name 'p_num' is not defined

### Comparison against author's dataset

In [1]:
import pandas as pd
readpath = r'C:\Users\Jurjen\Desktop\Python exercises code (target level)\cf-enhancement-xai\src\data\bank.csv'
df = pd.read_csv(readpath)
df = df.loc[:, df.columns != 'Unnamed: 0']
print(df.head())  # to display the first few rows
print(len(df.columns))

   age  Experience  Income  Family     CCAvg  Education  Mortgage  \
0   52          15     140       2  7.737671          2        32   
1   51           0     150       3  5.073039          1       328   
2   32          18     144       3  6.295617          3        59   
3   51          20     159       1  5.495390          3       275   
4   38          17     154       2  3.225856          3       189   

   SecuritiesAccount  CDAccount  Online  CreditCard  Personal Loan  
0                  1          1       1           0              1  
1                  1          1       0           1              1  
2                  0          1       0           1              1  
3                  0          1       1           0              1  
4                  1          1       1           1              1  
12


In [2]:
from sklearn.model_selection import train_test_split

X = df.loc[:, df.columns != 'Personal Loan']
y = df['Personal Loan']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

In [3]:
from src.data.load_data import preprocess_data
from src.data.load_data import preprocess_num

num_cols = ['age','Experience','Income','Family','CCAvg','Education','Mortgage']

X_train_raw,X_test_raw = X_train,X_test

X_train_num, X_test_num, datasetdf_num = preprocess_num(X_train, X_test, df, num_cols)
X_train, X_test, datasetdf = preprocess_data(X_train, X_test, df, num_cols)
print(X_train_num.head())

           age  Experience    Income    Family     CCAvg  Education  Mortgage  \
3865  0.984124    1.061265 -0.396133  0.487610 -0.135698  -1.344684 -0.780557   
5753 -0.294585   -0.374082 -0.663640  0.487610 -1.123458   1.216779  1.321462   
379  -0.111912   -1.360883  0.620392  1.411979  1.266926  -0.063953  0.689214   
2935 -0.385921   -0.463791  1.012735 -1.361130  1.152487   1.216779 -0.780557   
6186 -0.477258   -0.912337 -1.483993 -1.361130 -1.009661   1.216779  0.171920   

      SecuritiesAccount  CDAccount  Online  CreditCard  
3865                  0          0       1           0  
5753                  0          0       1           0  
379                   0          1       1           0  
2935                  0          1       1           0  
6186                  0          0       0           0  


In [4]:
from src.model.train_model import train_classifier_LR

clf = train_classifier_LR(X_train, y_train, random_state=42)
from sklearn.metrics import accuracy_score

y_pred = clf.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.9633507853403142


In [5]:
from src.ontology.generate_rules import *

X_train_positive = X_train_num[y_train == 1]
X_train_negative = X_train_num[y_train == 0]
positive_profile = summarize_features(X_train_positive)
positive_profile
negative_profile = summarize_features(X_train_negative)
negative_profile
#p_statistical = extract_statistical_rules(X_train_positive, X_train_raw, num_quantiles=(0.1, 0.9), cat_threshold=0.85)
p_statistical = extract_statistical_rules(X_train_positive, X_train_num, num_quantiles=(0.1, 0.9), cat_threshold=0.85)
p_statistical
p_permutation_imp_top_features = top_features(clf, X_train, y_train, n_repeats=5, random_state=42)
p_permutation_imp_top_features
p = combined_features(p_permutation_imp_top_features, p_statistical)
p_num = {key: value for key, value in p.items() if isinstance(value, tuple)}
p_cat = {key: value for key, value in p.items() if isinstance(value, str)}
print(p_num)
print(p_cat)

{'age': (np.float64(-1.299), np.float64(1.258)), 'Experience': (np.float64(-1.361), np.float64(1.33)), 'Income': (np.float64(0.424), np.float64(1.53)), 'Family': (np.float64(-1.361), np.float64(1.412)), 'CCAvg': (np.float64(0.053), np.float64(1.835)), 'Education': (np.float64(-0.064), np.float64(1.217)), 'Mortgage': (np.float64(-0.781), np.float64(2.069))}
{'CDAccount': '1'}


In [6]:
from src.utilities.desired_space import desired_space
X_test_negative = X_test[y_test==0]
x= X_test_negative[0:1] #test instance #select first row as dataFrame
p_num = p_num
p_cat = p_cat
space = datasetdf[datasetdf['Personal Loan'] == 1] #filter instances if they have the desired y
desired_space = space.drop(['Personal Loan'], axis=1) #drop y
#desired_space = desired_space(1,datasetdf) #did preprocessing also to datasetdf
#cat_f= X_train.select_dtypes(include=['bool']) #categorical features
cat_f = ['SecuritiesAccount', 'CDAccount', 'Online', 'CreditCard']
num_f = ['age', 'Experience', 'Income', 'Family', 'CCAvg', 'Education', 'Mortgage']
#num_f= X_train.select_dtypes(include=['int64', 'float64']) #numerical features
protect_f= [] # Personal status and sex (X_train.head() shows only 3 values (columns) while there are 5) #protected features
features= X_train.columns #all features
t= 1 #desired outcome
f= clf #black-box model for which we want to find CF
X= X_train #training data
step = {attribute:0.01 for attribute in p_num.keys()} #was 0.01

f2change = p.keys()

In [7]:
from src.utilities.UFCE import SF
#cf = SF(x,X,cat_f,p,f,t,step)
cf = SF(x,X_train,p_num,p_cat,f,t,step) # changed from X_train_raw to X_train
print(cf)

original x prediction:  [0]
all columns are 0 for this category, as it is the reference feature value


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LocalOutlierFactor was fitted with feature names
  warnings.warn(


[           age  Experience  Income   Family     CCAvg  Education  Mortgage  \
3478 -1.025276   -0.912337  1.2585  0.48761 -0.440675  -1.344684 -0.780557   

      SecuritiesAccount  CDAccount  Online  CreditCard  
3478                  0          0       0           0  ,            age  Experience    Income   Family     CCAvg  Education  Mortgage  \
3478 -1.025276   -0.912337  1.223313  0.48761 -0.440675  -1.344684 -0.780557   

      SecuritiesAccount  CDAccount  Online  CreditCard  
3478                  0          0       0           0  ]


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LocalOutlierFactor was fitted with feature names
  warnings.warn(


In [8]:
print(clf.predict(cf[0]))

[1]


In [9]:
from itertools import combinations
from src.utilities.mutual_information import mi_score
from src.utilities.mutual_information import MI

feature_pairs = list(combinations(list(features), 2))
print(feature_pairs[:5])
mi_list = MI(feature_pairs,
             X_train)  #used all features available #original authors do over entire X but it is not preprocessed... Which i think is nessecary? #also works for bool one-hot encoding 
# top 5 
print(mi_list[:5])
### Nearest Neighbour: KD Tree
from src.utilities.nearest_neighbours import FNN

nn = FNN(desired_space, x,
         3.5)  #radius arbitrarily set; can experiment with how close we want it to be to x #3.5 for euclidean distance is around 0.5 for each of the 48 features difference from x, get 3 datapoints
print(nn)
### Subspace: Intervals
from src.utilities.nearest_neighbours import intervals
from src.utilities.nearest_neighbours import intervals2

#subspace = intervals(nn,p,f2change,x) 
subspace = intervals2(nn, p_num, p_cat, f2change, x)
print(subspace)  #correct output

[('age', 'Experience'), ('age', 'Income'), ('age', 'Family'), ('age', 'CCAvg'), ('age', 'Education')]
[('age', 'Experience'), ('Income', 'CCAvg'), ('CCAvg', 'CDAccount'), ('Income', 'CDAccount'), ('Income', 'Mortgage')]
           age  Experience    Income    Family     CCAvg  Education  Mortgage  \
3762 -1.207948   -1.091755  0.031878 -0.436760  0.333147  -1.344684 -0.780557   
3861 -1.390621   -1.271173  0.281551 -0.436760 -0.076523  -0.063953 -0.780557   
4904 -1.664630   -1.540301  0.049712 -1.361130  0.014514  -0.063953 -0.780557   
6815 -1.481957   -1.540301 -0.199961 -1.361130  0.196590   1.216779 -0.780557   
3658 -1.664630   -1.540301  0.281551 -1.361130  0.151071  -0.063953 -0.780557   
...        ...         ...       ...       ...       ...        ...       ...   
1274 -0.385921    0.881846  0.477722  1.411979  0.932044  -0.063953  0.401829   
1586 -1.025276   -1.271173  0.745229 -0.436760  0.832978  -0.063953  1.305040   
1822 -0.842603   -0.284373  0.620392  1.411979  0.8

In [10]:
from src.utilities.UFCE import DF

CFs = DF(datasetdf, x, X_train, subspace, mi_list, cat_f, num_f, features, protect_f, f, t)
print(CFs)
print(len(CFs))

going to next feature pair
[[-0.46379103]
 [-1.80942831]
 [-0.19466357]
 ...
 [ 1.68922862]
 [ 1.77893777]
 [-1.4505917 ]]
going to next feature pair
[[ 2.17105047]
 [ 0.95813923]
 [ 1.51464319]
 ...
 [-1.2144962 ]
 [-1.12345838]
 [-0.98690166]]


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation

going to next feature pair
[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]
going to next feature pair
[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LocalOutlierFactor was fitted with feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LocalOutlierFactor was fitted with feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site

going to next feature pair
[[-0.5178044 ]
 [ 1.91265425]
 [-0.29610716]
 ...
 [-0.78055669]
 [-0.78055669]
 [-0.78055669]]


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LocalOutlierFactor was fitted with feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LocalOutlierFactor was fitted with feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-pac

going to next feature pair
[[-0.5178044 ]
 [ 1.91265425]
 [-0.29610716]
 ...
 [-0.78055669]
 [-0.78055669]
 [-0.78055669]]
going to next feature pair
[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\va

going to next feature pair
[[-0.0639527]
 [-1.3446842]
 [ 1.2167788]
 ...
 [ 1.2167788]
 [-0.0639527]
 [-1.3446842]]
going to next feature pair
[[ 2.17105047]
 [ 0.95813923]
 [ 1.51464319]
 ...
 [-1.2144962 ]
 [-1.12345838]
 [-0.98690166]]


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation

going to next feature pair
[[ 2.17105047]
 [ 0.95813923]
 [ 1.51464319]
 ...
 [-1.2144962 ]
 [-1.12345838]
 [-0.98690166]]
going to next feature pair
[[ 2.17105047]
 [ 0.95813923]
 [ 1.51464319]
 ...
 [-1.2144962 ]
 [-1.12345838]
 [-0.98690166]]
going to next feature pair
[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation

going to next feature pair
[[-0.5178044 ]
 [ 1.91265425]
 [-0.29610716]
 ...
 [-0.78055669]
 [-0.78055669]
 [-0.78055669]]
going to next feature pair
going to next feature pair
[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]
going to next feature pair


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation

[[-0.5178044 ]
 [ 1.91265425]
 [-0.29610716]
 ...
 [-0.78055669]
 [-0.78055669]
 [-0.78055669]]
going to next feature pair
[[-0.43676017]
 [ 0.48760958]
 [ 0.48760958]
 ...
 [-0.43676017]
 [ 0.48760958]
 [ 0.48760958]]


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation

going to next feature pair
[[-0.5178044 ]
 [ 1.91265425]
 [-0.29610716]
 ...
 [-0.78055669]
 [-0.78055669]
 [-0.78055669]]
going to next feature pair
[[-0.0639527]
 [-1.3446842]
 [ 1.2167788]
 ...
 [ 1.2167788]
 [-0.0639527]
 [-1.3446842]]


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LocalOutlierFactor was fitted with feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LocalOutlierFactor was fitted with feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-pac

going to next feature pair
[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]
going to next feature pair
[[-0.5178044 ]
 [ 1.91265425]
 [-0.29610716]
 ...
 [-0.78055669]
 [-0.78055669]
 [-0.78055669]]


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation

going to next feature pair
[[-0.43676017]
 [ 0.48760958]
 [ 0.48760958]
 ...
 [-0.43676017]
 [ 0.48760958]
 [ 0.48760958]]
going to next feature pair
[[ 0.67389366]
 [ 0.85223142]
 [ 0.74522877]
 ...
 [-1.39482435]
 [-0.94897995]
 [-0.34263157]]
going to next feature pair
going to next feature pair


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation

[[-0.0639527]
 [-1.3446842]
 [ 1.2167788]
 ...
 [ 1.2167788]
 [-0.0639527]
 [-1.3446842]]
going to next feature pair
[[-0.0639527]
 [-1.3446842]
 [ 1.2167788]
 ...
 [ 1.2167788]
 [-0.0639527]
 [-1.3446842]]
going to next feature pair
going to next feature pair
[[ 0.67389366]
 [ 0.85223142]
 [ 0.74522877]
 ...
 [-1.39482435]
 [-0.94897995]
 [-0.34263157]]


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation

going to next feature pair
[[-0.43676017]
 [ 0.48760958]
 [ 0.48760958]
 ...
 [-0.43676017]
 [ 0.48760958]
 [ 0.48760958]]
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
going to next feature pair
[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]
going to next feature pair
[[-0.0639527]
 [-1.3446842]
 [ 1.2167788]
 ...
 [ 1.2167788]
 [-0.0639527]
 [-1.3446842]]


C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\Jurjen\Desktop\Python exercises code (target level)\venv\lib\site-packages\sklearn\utils\validation

going to next feature pair
going to next feature pair
[           age  Experience  Income   Family     CCAvg  Education  Mortgage  \
3478 -1.025276   -0.912337    1.21  0.48761  0.618328  -1.344684 -0.780557   

      SecuritiesAccount  CDAccount  Online  CreditCard  
3478                  0          0       0           0  ,            age  Experience  Income   Family     CCAvg  Education  Mortgage  \
3478 -1.025276   -0.912337    1.21  0.48761  0.618328  -1.344684 -0.780557   

      SecuritiesAccount  CDAccount  Online  CreditCard  
3478                  0          0       0           0  ,            age  Experience  Income   Family     CCAvg  Education  Mortgage  \
3478 -1.025276   -0.912337    1.21  0.48761  0.618328  -1.344684 -0.780557   

      SecuritiesAccount  CDAccount  Online  CreditCard  
3478                  0          0       0           0  ,            age  Experience  Income   Family     CCAvg  Education  Mortgage  \
3478 -1.025276   -0.912337    1.21  0.48761  0.6183

In [11]:
import numpy as np

bad_CFs = []

for i, cf in enumerate(CFs):
    prediction = f.predict(cf)

    # If the model returns an array, extract the scalar
    if isinstance(prediction, (np.ndarray, list)):
        prediction = prediction[0]

    if prediction != t:
        print(f"CF #{i} has incorrect prediction: {prediction} (expected: {t})")
        bad_CFs.append((i, prediction))
        
if not bad_CFs:
    print("✅ All good: All CFs have prediction == t")

✅ All good: All CFs have prediction == t


In [15]:
print(x)
print(CFs[0])
print(t)
print(f.predict(CFs[0]))

           age  Experience    Income   Family     CCAvg  Education  Mortgage  \
3478 -1.025276   -0.912337 -0.859811  0.48761 -0.440675  -1.344684 -0.780557   

      SecuritiesAccount  CDAccount  Online  CreditCard  
3478                  0          0       0           0  
           age  Experience  Income   Family     CCAvg  Education  Mortgage  \
3478 -1.025276   -0.912337    1.21  0.48761  0.618328  -1.344684 -0.780557   

      SecuritiesAccount  CDAccount  Online  CreditCard  
3478                  0          0       0           0  
1
[1]


In [14]:
#print("original: ")
#print(x)
#print("counterfactual: ")
#print(z)
print("Differences between original and counterfactual:")

# Compare x and z for all columns
differences = (x != CFs[0]).iloc[0]

# Print only the differing columns with their values in x and z
for col in x.columns[differences]:
    print(f"{col}: original = {x.iloc[0][col]}, counterfactual = {CFs[0].iloc[0][col]}")

Differences between original and counterfactual:


NameError: name 'CFs' is not defined

In [38]:
from src.data.load_data import preprocess_bank
features, catf, numf, uf, f2change, outcome_label, desired_outcome, nbr_features, protectf, data_lab0, data_lab1 = preprocess_bank(df)

NameError: name 'df' is not defined